import clsx from "clsx";
import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const iranSans = localFont({
  src: [
    { path: "../public/fonts/IRANSansX-Regular.ttf", style: "normal" },
    {
      path: "../public/fonts/IRANSansX-Bold.ttf",
      style: "bold",
    },
    { path: "../public/fonts/IRANSansXFaNum-Regular.ttf", style: "normal" },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, iranSans.className)}>
        {children}
      </body>
    </html>
  );
}
